exclude_patterns: [lecture02/transformations.ipynb]

execute:
  execute_notebooks: 'off' # toggle between 'off' and auto  to disable or enable execution of jupyter nbs during book building   
  allow_errors: true

parse:
  myst_enable_extensions:
    - amsmath
  myst_extended_syntax: true
  
#######################################################################################
# Book settings
title                       : Maths for Biologists  # The title of the book. Will be placed in the left navbar.
author                      : Lucas D. Fernandes (adapted by Alexander Kier Christensen  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        :   # A path to the book logo
